---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define phpmyadmin_config_file.
  set_fact:
    phpmyadmin_config_file: "{{ __phpmyadmin_config_file }}"
  when: phpmyadmin_config_file is not defined

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Add default username and password for MySQL connection.
  ansible.builtin.template:
    src: config-db.php.j2
    dest: "{{ phpmyadmin_config_file }}"
    owner: root
    group: root
    mode: 0644
